version: '3.3'
services:
  merritt-maven:
    container_name: merritt-maven
    image: ${ECR_REGISTRY}/merritt-maven:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_RELEASE_ARG: ${JAVA_RELEASE:-8}