version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo

phases:
  pre_build:
    on-failure: ABORT
    commands:
    - COMMIT=`git rev-parse --short HEAD`
    - # Get semantic tags for commit otherwise get all tags for commit, sort and choose the last value
    - TAG=`(git tag --contains $COMMIT | egrep "^[0-9]+\.[0-9]+\.[0-9]+$" || git tag --contains $COMMIT || echo '') | sort | tail -1`
    - |
      if [[ "$MODE" == "OnPush" ]]
      then
        # Get Tag || Get Branch || Alternate Branch Lookup || Get Committ
        BRANCHTAG=`echo $TAG | grep . || git symbolic-ref -q --short HEAD || git name-rev $(git rev-parse --short HEAD) | cut -d' ' -f2 || git rev-parse --short HEAD`
      else
        BRANCHTAG=$BRANCHNAME
      fi
    - echo "Branchtag ${BRANCHTAG}; COMMITDATE=${COMMITDATE}; REPONAME=${REPONAME}; BRANCHNAME=${BRANCHNAME}"

    - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain cdlib-uc3-mrt --domain-owner $AWS_ACCOUNT_ID --region $AWS_REGION --query authorizationToken --output text`
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_REGISTRY}


  build:
    on-failure: ABORT
    commands:
    - |
      docker compose build --push --quiet \
        -f mrt-inttest-services/docker-compose.yml

    - |
      docker build --push --quiet \
        -t ${ECR_REGISTRY}/mrt-database \
        mrt-services/mysql
    - |
      docker build --push --quiet \
        -t ${ECR_REGISTRY}/mrt-opendj \
        --build-arg ECR_REGISTRY=${ECR_REGISTRY} \
        mrt-services/ldap
    - |
      docker build --push --quiet \
        -t ${ECR_REGISTRY}/mrt-init \
        mrt-services/merritt-init
    - |
      docker build --push --quiet \
        -t ${ECR_REGISTRY}/callback \
        mrt-services/callback
