version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain cdlib-uc3-mrt --domain-owner $AWS_ACCOUNT_ID --region $AWS_REGION --query authorizationToken --output text`
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_REGISTRY}

      - aws ecr create-repository --repository-name merritt-tomcat || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name merritt-maven || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mock-merritt-it || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-it-database || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-it-database-audit-replic || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-minio-it || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-minio-it-with-content || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name fakesmtp || echo 'ignore if exists...'

      - aws ecr create-repository --repository-name callback || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-opendj || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-init || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-database || echo 'ignore if exists...'

  build:
    on-failure: ABORT
    commands:
      - docker buildx create --use 
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/merritt-maven:dev \
          --build-arg JAVA_RELEASE_ARG=${JAVA_RELEASE:-8} \
          --push mrt-inttest-services/merritt-maven
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/merritt-tomcat:dev \
          --push mrt-inttest-services/merritt-tomcat
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/mock-merritt-it:dev \
          --push mrt-inttest-services/mock-merritt-it
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/mrt-it-database:dev \
          --push mrt-inttest-services/mrt-it-database
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/mrt-it-database-audit-replic:dev \
          --build-arg LOAD_SQL=/tmp/audit_replic_data.sql \
          --push mrt-inttest-services/mrt-it-database
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/mrt-minio-it:dev \
          --push mrt-inttest-services/mrt-minio-it
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/mrt-minio-it-with-content:dev \
          --build-arg ECR_REGISTRY=${ECR_REGISTRY} \
          --push mrt-inttest-services/mrt-minio-it-with-content

      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/mrt-database \
          --push mrt-services/mysql
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/mrt-opendj \
          --push mrt-services/ldap
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/mrt-init \
          --push mrt-services/merritt-init
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/callback \
          --push mrt-services/callback

  post_build:
    # this build may fail due to rate limits
    # on-failure: ABORT
    commands:
      - docker buildx create --use 
      - |
        docker buildx build --platform linux/arm64,linux/amd64 \
          -t ${ECR_REGISTRY}/fakesmtp:dev \
          --push mrt-inttest-services/fakesmtp
