build-config:
  main:
    tags:
      mrt-core: main
      mrt-cloud: main
      cdl-zk-queue: main
      mrt-zoo: main
      mrt-inventory: main
      mrt-store: main
      mrt-ingest: main
      mrt-audit: main
      mrt-replic: main
      mrt-dashboard: main
      mrt-integ-tests: main
    # docker-tag: dev
    # artifacts-tag: testall
    push: true
    scan-unfixable: true
    scan-fixable: true
    run-maven: true
    run-maven-tests: true
  main-buildonly:
    tags:
      mrt-core: main
      mrt-cloud: main
      cdl-zk-queue: main
      mrt-zoo: main
      mrt-inventory: main
      mrt-store: main
      mrt-ingest: main
      mrt-audit: main
      mrt-replic: main
      mrt-dashboard: main
      mrt-integ-tests: main
    # docker-tag: dev
    # artifacts-tag: testall
    push: false
    scan-unfixable: false
    scan-fixable: false
    run-maven: true
    run-maven-tests: false
  # create alternative branch configs
  # --------------------------------
  # opensearch:
  #   tags:
  #     mrt-core: main
  #     mrt-cloud: main
