version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain cdlib-uc3-mrt --domain-owner $AWS_ACCOUNT_ID --region us-west-2 --query authorizationToken --output text`
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_REGISTRY}

      - aws ecr create-repository --repository-name mrt-tomcat || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-maven || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mock-merritt-it || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-it-database || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-minio-it || echo 'ignore if exists...'
      - aws ecr create-repository --repository-name mrt-minio-it-with-content || echo 'ignore if exists...'

  build:
    on-failure: ABORT
    commands:
      - docker-compose -f mrt-inttest-services/mrt-tomcat/docker-compose.yml build
      - docker-compose -f mrt-inttest-services/mrt-tomcat/docker-compose.yml push
      - docker-compose -f mrt-inttest-services/mrt-maven/docker-compose.yml build
      - docker-compose -f mrt-inttest-services/mrt-maven/docker-compose.yml push
      - docker-compose -f mrt-inttest-services/mock-merritt-it/docker-compose.yml build
      - docker-compose -f mrt-inttest-services/mock-merritt-it/docker-compose.yml push
      - docker-compose -f mrt-inttest-services/mrt-it-database/docker-compose.yml build
      - docker-compose -f mrt-inttest-services/mrt-it-database/docker-compose.yml push
      - docker-compose -f mrt-inttest-services/mrt-minio-it/docker-compose.yml build
      - docker-compose -f mrt-inttest-services/mrt-minio-it/docker-compose.yml push
      - docker-compose -f mrt-inttest-services/mrt-minio-it-with-content/docker-compose.yml build
      - docker-compose -f mrt-inttest-services/mrt-minio-it-with-content/docker-compose.yml push
  post_build:
    commands:
      #- aws s3 rm s3://${S3CFBUCKET}/api --recursive
