# Merritt Build Configurations 
#   Construct a new grouping of tags if you wish to build a different combination of branches
#
# Possible future flags
# - docker-tag - to build tags other than "dev"

# Common sets of build flags to be used in comination with a set of branches and tags
flagsets:
  main: &main
    description: "Complete build and test of docker stack images and maven assets.  Scan ALL docker images."
    push: true
    build-it: true
    build-stack: true
    scan-unfixable: true
    scan-fixable: true
    run-maven: true
    run-maven-tests: true
  docker: &docker
    description: "Build docker images and push to ECR"
    build-it: true
    build-stack: true
    push: true
    scan-unfixable: false
    scan-fixable: false
    run-maven: false
    run-maven-tests: false
    build-support: false
  docker-nopush: &docker-nopush
    description: "Build docker images.  Do not push to ECR"
    build-it: true
    build-stack: true
    push: false
    scan-unfixable: false
    scan-fixable: false
    run-maven: false
    run-maven-tests: false
    build-support: false
  scan: &scan
    description: "Build docker images and scan for vulnerabilities"
    build-it: true
    build-stack: true
    push: false
    scan-unfixable: true
    scan-fixable: true
    run-maven: false
    run-maven-tests: false
    build-support: false
  buildonly: &buildonly
    description: "Run docker and maven builds.  No tests.  No scans."
    build-it: true
    build-stack: true
    push: false
    scan-unfixable: false
    scan-fixable: false
    run-maven: true
    run-maven-tests: false
    build-support: false
  mvn: &mvn
    description: "Run maven builds only.  No tests."
    build-it: true
    build-stack: false
    push: false
    scan-unfixable: false
    scan-fixable: false
    run-maven: true
    run-maven-tests: false
    build-support: false
  sbox: &sbox
    description: "Run maven builds and tests. Pull IT images from ECR"
    build-it: false
    build-stack: false
    push: false
    scan-unfixable: false
    scan-fixable: false
    run-maven: true
    run-maven-tests: true
    build-support: false
  buildtest: &buildtest
    description: "Run docker builds and maven builds and tests."
    build-it: true
    build-stack: true
    push: false
    scan-unfixable: false
    scan-fixable: false
    run-maven: true
    run-maven-tests: true
    build-support: false
  jenkins: &jenkins
    description: "Jenkins build: run maven builds and tests"
    build-it: true
    build-stack: false
    push: false
    scan-unfixable: false
    scan-fixable: false
    run-maven: true
    run-maven-tests: true
    build-support: false
build-config:
  main:
    <<: *main
    tags: &maintags
      mrt-core: main
      mrt-cloud: main
      cdl-zk-queue: main
      mrt-zoo: main
      mrt-inventory: main
      mrt-store: main
      mrt-ingest: main
      mrt-audit: main
      mrt-replic: main
      mrt-dashboard: main
      mrt-integ-tests: main
  main-docker:
    <<: *docker
    tags:
      <<: *maintags
  main-docker-nopush:
    <<: *docker-nopush
    tags:
      <<: *maintags
  main-scan:
    <<: *scan
    tags:
      <<: *maintags
  main-buildonly:
    <<: *buildonly
    tags:
      <<: *maintags
  main-buildtest:
    <<: *buildtest
    tags:
      <<: *maintags
  main-mvn:
    <<: *mvn
    tags:
      <<: *maintags
  main-jenkins:
    <<: *jenkins
    tags:
      <<: *maintags
  java11-main:
    <<: *main
    tags: &java11tags
      mrt-core: java11
      mrt-cloud: java11
      cdl-zk-queue: java11
      mrt-zoo: java11
      mrt-inventory: java11
      mrt-store: java11
      mrt-ingest: java11
      mrt-audit: java11
      mrt-replic: java11
      mrt-dashboard: main
      mrt-integ-tests: main
  java11-jenkins:
    <<: *jenkins
    tags: 
      <<: *java11tags
