# Merritt Build Configurations 
#   Construct a new grouping of tags if you wish to build a different combination of branches
#
# Possible future flags
# - docker-tag - to build tags other than "dev"

# Common sets of build flags to be used in comination with a set of branches and tags
flagsets:
  # run only docker builds, do not run maven
  docker: &docker
    build-stack: true
    push: true
    scan-unfixable: false
    scan-fixable: false
    run-maven: false
    run-maven-tests: false
    build-support: false
  # run docker and maven buids
  buildonly: &buildonly
    build-stack: true
    push: false
    scan-unfixable: false
    scan-fixable: false
    run-maven: true
    run-maven-tests: false
    build-support: false
  # run docker and maven builds, include maven tests
  buildtest: &buildtest
    build-stack: true
    push: false
    scan-unfixable: false
    scan-fixable: false
    run-maven: true
    run-maven-tests: true
    build-support: false
  jenkins: &jenkins
    build-stack: false
    push: false
    scan-unfixable: false
    scan-fixable: false
    run-maven: true
    run-maven-tests: true
build-config:
  main:
    tags: &maintags
      mrt-core: main
      mrt-cloud: main
      cdl-zk-queue: main
      mrt-zoo: main
      mrt-inventory: main
      mrt-store: main
      mrt-ingest: main
      mrt-audit: main
      mrt-replic: main
      mrt-dashboard: main
      mrt-integ-tests: main
    push: true
    build-stack: true
    scan-unfixable: true
    scan-fixable: true
    run-maven: true
    run-maven-tests: true
    build-support: true
  main-docker:
    <<: *docker
    tags:
      <<: *maintags
  main-buildonly:
    <<: *buildonly
    tags:
      <<: *maintags
  main-test:
    <<: *buildtest
    tags:
      <<: *maintags
  main-jenkins:
    <<: *jenkins
    tags:
      <<: *maintags
  newbuild-buildonly:
    <<: *buildonly
    tags: &newbuildtags
      mrt-core: newbuild
      mrt-cloud: newbuild
      cdl-zk-queue: main
      mrt-zoo: main
      mrt-inventory: main
      mrt-store: main
      mrt-ingest: main
      mrt-audit: main
      mrt-replic: main
      mrt-dashboard: main
      mrt-integ-tests: main
  newbuild-test:
    <<: *buildtest
    tags:
      <<: *newbuildtags
  newbuild-jenkins:
    <<: *jenkins
    tags:
      <<: *newbuildtags
