#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
# This adds apache to the front of the merritt docker stack.  
# This is useful for testing character encoding impacts from apache as is done when accessing a ui server directly
version: '3.9'
services:
  apache:
    container_name: apache
    depends_on:
    - ui
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mrt-apache
    build:
      context: apache
      dockerfile: Dockerfile
    networks:
      merrittnet:
    ports:
    - published: 8099
      target: 8099
    restart: unless-stopped
    stdin_open: true
    tty: true

