#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.7'
services:
  replic:
    image: cdluc3/mrt-replic
    build:
      context: replic
      dockerfile: Dockerfile
    restart: unless-stopped
  audit:
    image: cdluc3/mrt-audit
    build:
      context: audit
      dockerfile: Dockerfile
    restart: unless-stopped
