#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.7'
services:
  oai:
    container_name: oai
    image: cdluc3/mrt-oai
    build:
      context: oai
      dockerfile: Dockerfile
    networks:
      merrittnet:
    ports:
    - published: 8083
      target: 8080
    stdin_open: true
    tty: true
  sword:
    container_name: sword
    image: cdluc3/mrt-sword
    build:
      context: sword
      dockerfile: Dockerfile
    networks:
      merrittnet:
    ports:
    - published: 8084
      target: 8080
    stdin_open: true
    tty: true
