#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.7'
volumes:
  dryad-db:
  dryad-solr:
services:
  oai:
    container_name: oai
    image: cdluc3/mrt-oai
    build:
      context: oai
      dockerfile: Dockerfile
    networks:
      merrittnet:
    ports:
    - published: 8083
      target: 8080
    restart: unless-stopped
    stdin_open: true
    tty: true
  sword:
    container_name: sword
    image: cdluc3/mrt-sword
    build:
      context: sword
      dockerfile: Dockerfile
    networks:
      merrittnet:
    ports:
    - published: 8084
      target: 8080
    restart: unless-stopped
    stdin_open: true
    tty: true
  dryad:
    container_name: dryad
    image: cdluc3/dryad
    build:
      context: dryad
      dockerfile: Dockerfile
    networks:
      merrittnet:
        aliases:
        - my-minio-localhost-alias
        - ${HOSTNAME}
    volumes:
    - type: bind
      source: ./no-track/dryad/app_config.yml
      target: /var/www/app_name/config/app_config.yml
    - type: bind
      source: ./no-track/dryad/tenants/dryad.yml
      target: /var/www/app_name/config/tenants/dryad.yml
    ports:
    - published: 8087
      target: 3000
    environment:
      TEST_LOGIN: 'test'
    restart: unless-stopped
    stdin_open: true
    tty: true
    entrypoint:
      - /bin/bash
      - '-c'
      - |
          bundle exec rake db:migrate
          bundle exec passenger start
  dryad-db:
    container_name: dryad-db
    image: mysql:5.7
    networks:
      merrittnet:
    restart: always
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: 'dryad'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root-password'
    ports:
    - published: 3307
      target: 3306
    security_opt:
      - seccomp:unconfined
    volumes:
    - dryad-db:/var/lib/mysql
  solr:
    container_name: solr
    image: cdluc3/dryad-solr
    build:
      context: dryad-solr
      dockerfile: Dockerfile
    networks:
      merrittnet:
    restart: always
    ports:
    - published: 8085
      target: 8983
    volumes:
    - dryad-solr:/var/solr/data/geoblacklight/data
  merritt-init:
    depends_on:
    - oai
    entrypoint:
      - /bin/bash
      - '-c'
      - |
          echo "*** Merritt + Dryad Initialization"
          echo "    ------------------------------"
          echo "*** Pause 30 seconds then init the inventory service"
          sleep 30
          echo "*** Starting the inventory service"
          curl -v -X POST http://inventory:8080/inventory/service/start?t=json
          echo "*** Pause 30 seconds then ping the OAI service"
          sleep 30
          echo "*** Prompt OAI service"
          curl -v -H "Content-Type: application/xml" http://oai:8080/oai/oai/v2?verb=Identify
          sleep 30
          echo "*** Prompt OAI service - repeat"
          curl -v -H "Content-Type: application/xml" http://oai:8080/oai/oai/v2?verb=Identify
          echo "*** Service Init Complete"

