#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.7'
services:
  apache:
    volumes:
    - type: bind
      source: ./no-track/mrt-ec2.conf
      target: /usr/local/apache2/conf/conf.d/mrt.conf
  store:
    environment:
      MRT_DOCKER_HOST: localhost
    networks:
      merrittnet:
        aliases:
        - my-minio-localhost-alias
          localhost
  ui:
    environment:
      MRT_DOCKER_HOST: localhost
    networks:
      merrittnet:
        aliases:
        - my-minio-localhost-alias
          localhost
  minio:
    networks:
      merrittnet:
        aliases:
        - my-minio-localhost-alias
          localhost

