#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.7'
services:
  store:
    environment:
      MRT_DOCKER_HOST: my-minio-localhost-alias
      MRT_MINIO_PORT: 9000
    networks:
      merrittnet:
        aliases:
        - my-minio-localhost-alias
        - ${HOSTNAME:-localhost}
  ui:
    environment:
      MRT_DOCKER_HOST: localhost
    networks:
      merrittnet:
        aliases:
        - my-minio-localhost-alias
        - ${HOSTNAME:-localhost}
  minio:
    networks:
      merrittnet:
        aliases:
        - my-minio-localhost-alias
        - ${HOSTNAME:-localhost}

