# This docker-compose file launches a minimal opensearch stack:
# - opensearch engine
# - opensearch dashboards
# - logstash
#
# In addition it adds overlay configs to various of the merritt micro-service containers
# to add logging configuration options.  This sets up log indexing for these containers.
#
version: '3'

volumes:
  opensearch-data1:

networks:
  merrittnet:

services:
  opensearch:
    image: opensearchproject/opensearch:1.2.4
    container_name: opensearch
    environment:
    - cluster.name=opensearch-cluster
    - node.name=opensearch
    - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
    - "OPENSEARCH_JAVA_OPTS=-Xms4096m -Xmx4096m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
    - opensearch-data1:/usr/share/opensearch/data
    ports:
    - published: 9200
      target: 9200
    networks:
      merrittnet:

  logstash:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/logstash-oss:dev
    container_name: logstash
    build:
      context: opensearch/logstash
      dockerfile: Dockerfile
    ports:
    - published: 5044
      target: 5044
    - published: 12201
      target: 12201
      protocol: udp
    networks:
      merrittnet:
    depends_on:
    - opensearch

  opensearch-dashboards:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/opensearch-dashboards:dev
    container_name: opensearch-dashboards
    build:
      context: opensearch/opensearch-dashboards
      dockerfile: Dockerfile
    ports:
    - published: 8094
      target: 5601
    expose:
      - "8094"
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch:9200"]'
    networks:
      merrittnet:
    depends_on:
    - opensearch
    - logstash


  # Overlay logging configs to merritt containers
  #
  apache:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  ingest:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  store:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  inventory:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  ui:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  replic:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  audit:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
