# This docker-compose file launches a minimal opensearch stack:
# - opensearch engine
# - opensearch dashboards
# - logstash
#
# In addition it adds overlay configs to various of the merritt micro-service containers
# to add logging configuration options.  This sets up log indexing for these containers.
#
version: '3'

volumes:
  apps-logs-ingest:
  apps-logs-store:
  apps-logs-inventory:
  apps-logs-audit:
  apps-logs-replic:
  apps-logs-ui:

networks:
  merrittnet:

services:
  opensearch:
    image: opensearchproject/opensearch
    container_name: opensearch
    environment:
    - cluster.name=opensearch-cluster
    - node.name=opensearch
    - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
    - "OPENSEARCH_JAVA_OPTS=-Xms4096m -Xmx4096m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
    - published: 9200
      target: 9200
    networks:
      merrittnet:
    restart: unless-stopped

  logstash:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/logstash-oss:dev
    container_name: logstash
    build:
      context: opensearch/logstash
      dockerfile: Dockerfile
    ports:
    - published: 5044
      target: 5044
    - published: 12201
      target: 12201
      protocol: udp
    networks:
      merrittnet:
    volumes:
    - "apps-logs-ingest:/logfiles/ingest/"
    - "apps-logs-store:/logfiles/store/"
    - "apps-logs-inventory:/logfiles/inventory/"
    - "apps-logs-audit:/logfiles/audit/"
    - "apps-logs-replic:/logfiles/replic/"
    - "apps-logs-ui:/logfiles/ui/"
    depends_on:
    - opensearch
    restart: unless-stopped

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards
    container_name: opensearch-dashboards
    ports:
    - published: 8094
      target: 5601
    expose:
      - "8094"
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch:9200"]'
    networks:
      merrittnet:
    depends_on:
    - opensearch
    - logstash
    restart: unless-stopped

  ingest:
    volumes:
    - "apps-logs-ingest:/usr/local/tomcat/logs/"
  store:
    volumes:
    - "apps-logs-store:/usr/local/tomcat/logs/"
  inventory:
    volumes:
    - "apps-logs-inventory:/usr/local/tomcat/logs/"
  ui:
    volumes:
    - "apps-logs-ui:/var/www/app_name/log/"
  replic:
    volumes:
    - "apps-logs-replic:/usr/local/tomcat/logs/"
  audit:
    volumes:
    - "apps-logs-audit:/usr/local/tomcat/logs/"
