services:
  merritt-coder:
    container_name: merritt-coder
    image: ${ECR_REGISTRY}/merritt-coder:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ECR_REGISTRY: ${ECR_REGISTRY}
    ports:
    - published: 8097
      target: 8080
