#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
# docker build --build-arg ECR_REGISTRY=${ECR_REGISTRY} -t ${ECR_REGISTRY}/mrt-inventory-src:dev -f Dockerfile-jar .
# aws ecr create-repository --repository-name mrt-inventory-src
# docker push ${ECR_REGISTRY}/mrt-inventory-src:dev

ARG ECR_REGISTRY=ecr_registry_not_set

FROM ${ECR_REGISTRY}/mrt-cloud:dev as build

WORKDIR /build/mrt-inventory

ADD mrt-inventory /build/mrt-inventory

RUN mvn install -D=environment=local -DskipITs -Ddocker.skip && \
    date -r inv-src/target +'mrt-inv: %Y-%m-%d:%H:%M:%S' >> /build/static/build.content.txt && \
    mvn clean && \
    rm -rf /root/.m2/repository/org/codehaus && \
    rm -rf /root/.m2/repository/org/apache/maven && \
    rm -rf /root/.m2/repository/commons-collections && \
    rm -rf /root/.m2/repository/com/google/cloud/tools && \
    rm -rf /root/.m2/repository/org/yaml/snakeyaml/1.26
