#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************

version: '3.7'
services:
  dependencies:
    image: cdluc3/mrt-dependencies
    build:
      context: .
      dockerfile: Dockerfile
