From docker.io/opensearchproject/opensearch-dashboards:1.2.0
#COPY --chown=opensearch-dashboards:opensearch-dashboards ./opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
