version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo
# - Grant CodeBuild project ECR List/Read/Write/Tag access to repos

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - export AWS_ACCOUNT_ID=`aws sts get-caller-identity| jq -r .Account`
      - echo AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - docker-compose -f mrt-inttest-services/mock-merritt-it/docker-compose.yml build --pull     
      - docker-compose -f mrt-inttest-services/mock-merritt-it/docker-compose.yml push     

      - docker-compose -f mrt-inttest-services/mrt-it-database/docker-compose.yml build --pull     
      - docker-compose -f mrt-inttest-services/mrt-it-database/docker-compose.yml push    
      - docker-compose -f mrt-inttest-services/mrt-it-database/docker-compose-audit-replic.yml build --pull
      - docker-compose -f mrt-inttest-services/mrt-it-database/docker-compose-audit-replic.yml push

      - docker-compose -f mrt-inttest-services/mrt-minio-it/docker-compose.yml build --pull
      - docker-compose -f mrt-inttest-services/mrt-minio-it/docker-compose.yml push

      - docker-compose -f mrt-inttest-services/mrt-minio-it-with-content/docker-compose.yml build --pull
      - docker-compose -f mrt-inttest-services/mrt-minio-it-with-content/docker-compose.yml push

      - docker-compose -f mrt-inttest-services/pm-server/docker-compose.yml build --pull
      - docker-compose -f mrt-inttest-services/pm-server/docker-compose.yml push
#  post_build:
#    commands:




