services:
  merritt-tomcat:
    container_name: merritt-tomcat
    image: ${ECR_REGISTRY}/merritt-tomcat:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - published: 8080
      target: 8080
