version: '3.3'
services:
  minio-server:
    container_name: merritt-tomcat
    image: ${ECR_REGISTRY}/merritt-tomcat:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ECR_REGISTRY: ${ECR_REGISTRY}
    ports:
    - published: 8080
      target: 8080
