
default: &default
  pool: 40
  timeout: 10000
  adapter: mysql2
  database: dryad
  username: user
  port: 3306
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true
  host: dryad-db
  password: password

development: &DEVELOPMENT
  <<: *default

local:
  <<: *default

local_dev:
  <<: *DEVELOPMENT

test:
  <<: *default
