#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
defaults: &defaults
  # maximum byte size threshold for download of object/versions without compression
  max_archive_size:     1073741824  # 1073741824 bytes = 1 GiB
  # maximum byte size threshold for any download whatsoever
  max_download_size:    322122547200  # 322122547200 bytes = 300 GiB
  dua_email_from:       no-reply-merritt@ucop.edu
  mrt_dua_file:         producer/mrt-dua.txt
  get_storage_key_file: "/api/get-storage-key-file"
  proto_force:          ""

docker: &docker
  <<: *defaults
  max_archive_size:  10000000  # 9999 bytes ~= 99 KiB
  max_download_size: 20000000  # 1048576 bytes = 1 MiB
  dua_email_to:         [no-email@ucop.edu]
  lostorage_email_to:   [no-email@ucop.edu]
  lostorage_email_from: no-email@ucop.edu
  merritt_server:       "http://localhost:8089"
  # In stage/prod, this url points to an Apache rule in the UI load balancer
  # that redirects to storge.
  # In Docker, point to an apache container
  container_url:        "http://localhost:8086/cloudcontainer/"
  n2t_uri:              "http://n2t-wf.cdlib.org/"
  # Note that the following service is no longer available
  mint_service:         "http://merritt-dev.cdlib.org:33121/request-identifier"
  ingest_service:       "http://ingest:8080/ingest/poster/submit/"
  ingest_service_update: "http://ingest:8080/ingest/poster/update/"
  uri_1:                "http://store:8080/store/content/"
  uri_2:                "http://store:8080/store/producer/"
  uri_3:                "http://store:8080/store/manifest/"
  storage_presign_file: "http://store:8080/store/presign-file/"
  storage_presign_obj:  "http://store:8080/store/presign-obj/"
  storage_presign_token: "http://store:8080/store/presign-obj-by-token/"

development: &development
  <<: *docker

test:
  <<: *development
  max_archive_size:     536870912  # 536870912 bytes = 512 MiB
  max_download_size:    5368709120  # 5368709120 bytes = 5 GiB
local:
  <<: *development

# TODO: rename uri_[1-3] to [content, producer, manifest]_uri or similar
