#filebeat.inputs:
#  - type: docker
#    containers:
#      path: "/usr/share/dockerlogs/data"
#      stream: "stdout"
#      ids:
#        - "*"
#      cri.parse_flags: true
#      combine_partial: true
#      exclude_files: ['.gz$']
#

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
 
processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
 
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
 
output.logstash:
  hosts: ["logstash:5044"]
 
#log files:
#logging.level: error
#logging.to_files: false
#logging.to_syslog: false
#loggins.metrice.enabled: false
#logging.files:
#  path: /var/log/filebeat
#  name: filebeat
#  keepfiles: 7
#  permissions: 0644
ssl.verification_mode: none
