#*********************************************************************
#   Copyright 2020 Regents of the University of California
#   All rights reserved
#*********************************************************************
networks:
  merrittnet:
services:
  callback:
    networks:
      merrittnet:
    container_name: callback
    image: ${ECR_REGISTRY}/callback
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - published: 8098
      target: 8098
    stdin_open: true
    tty: true
