version: '3.3'
services:
  db-container:
    container_name: mrt-it-database-audit-replic
    image: ${ECR_REGISTRY}/mrt-it-database-audit-replic:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LOAD_SQL: /tmp/audit_replic_data.sql
    restart: always
    environment:
      MYSQL_DATABASE: 'inv'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root-password'
