services:
  db-container:
    container_name: mrt-it-database
    image: ${ECR_REGISTRY}/mrt-it-database:dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'inv'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root-password'
