version: '3.9'
services:
  db-container:
    container_name: mrt-it-database
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mrt-it-database:dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'inv'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root-password'
